// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrqqXtJNo56KrB2f6oBNEk-PkGgoDWSx8',
    appId: '1:281295884415:web:8e5bc0bacd74669ca76f4a',
    messagingSenderId: '281295884415',
    projectId: 'health-9cd54',
    authDomain: 'health-9cd54.firebaseapp.com',
    databaseURL: 'https://health-9cd54-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'health-9cd54.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-9TeSG2XJZHyMzIvsrG-5r61P1qw-sV0',
    appId: '1:281295884415:android:55bb8fc75b297537a76f4a',
    messagingSenderId: '281295884415',
    projectId: 'health-9cd54',
    databaseURL: 'https://health-9cd54-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'health-9cd54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWzVKUbzuthwSBdZwh-hOuv8mZiT0u6gc',
    appId: '1:281295884415:ios:2619a5da798f88f0a76f4a',
    messagingSenderId: '281295884415',
    projectId: 'health-9cd54',
    databaseURL: 'https://health-9cd54-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'health-9cd54.appspot.com',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWzVKUbzuthwSBdZwh-hOuv8mZiT0u6gc',
    appId: '1:281295884415:ios:a92eb0cbd4b116a4a76f4a',
    messagingSenderId: '281295884415',
    projectId: 'health-9cd54',
    databaseURL: 'https://health-9cd54-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'health-9cd54.appspot.com',
    iosBundleId: 'com.example.client.RunnerTests',
  );
}
